import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from "next/link";

export default function Home() {
   return (
     <div className="">
        <Head>
           <title>Create Next App</title>
           <meta name="description" content="Generated by create next app"/>
           <link rel="icon" href="/favicon.ico"/>
        </Head>

        <main className="mt-24">
           <section className="text-gray-600 body-font">
              <div className="container px-5 py-0 mx-auto">
                 <div className="flex flex-col text-center w-full mb-20">
                    <h2 className="text-xs text-indigo-500 tracking-widest font-medium title-font mb-1">BASIT TAILWIND
                       COMPONENTLERI</h2>
                    <h1 className="sm:text-3xl text-2xl font-medium title-font text-gray-900">ISA OZSOY</h1>
                 </div>
                 <div className="flex flex-wrap -m-4">
                    <div className="p-4 md:w-1/3">
                       <div className="flex rounded-lg h-full bg-gray-100 p-8 flex-col">
                          <div className="flex items-center mb-3">
                             <div
                               className="
                               w-8 h-8 mr-3
                               inline-flex
                               items-center
                               justify-center
                               rounded-full
                               bg-indigo-500
                               text-white
                               flex-shrink-0
                               sm:w-15 sm:order-none order-first sm:h-15 animate-bounce  h-15 w-15 sm:ml-1 inline-flex items-center justify-center rounded-full bg-indigo-700 text-white flex-shrink-0
                               ">
                                <svg fill="none" stroke="currentColor" className="w-5 h-5" viewBox="0 0 24 24">
                                   <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                                </svg>
                             </div>
                             <h2 className="text-gray-900 text-lg title-font font-medium mb-2">Card</h2>
                          </div>
                          <div className="flex-grow">
                             <p className="leading-relaxed text-base">Lorem Ipsum bottle crucifix vinyl post-ironic four dollar
                                toast
                                vegan taxidermy. Gastropub indxgo juice poutine.</p>
                             <Link href="/card"><a className="mt-3 text-indigo-500 inline-flex items-center">Example
                                <svg fill="none" stroke="currentColor"
                                     className="w-4 h-4 ml-2 w-4 animate-ping h-4 ml-2" viewBox="0 0 24 24">
                                   <path d="M5 12h14M12 5l7 7-7 7"></path>
                                </svg>
                             </a></Link>
                          </div>
                       </div>
                    </div>
                    <div className="p-4 md:w-1/3">
                       <div className="flex rounded-lg h-full bg-gray-100 p-8 flex-col">
                          <div className="flex items-center mb-3">
                             <div
                               className="
                               w-8 h-8 mr-3
                               inline-flex
                               items-center
                               justify-center
                               rounded-full
                               bg-indigo-500
                               text-white
                               flex-shrink-0
                               sm:w-15 sm:order-none order-first sm:h-15 animate-bounce  h-15 w-15 sm:ml-1 inline-flex items-center justify-center rounded-full bg-indigo-700 text-white flex-shrink-0
                               ">
                                <svg fill="none" stroke="currentColor" className="w-5 h-5" viewBox="0 0 24 24">
                                   <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
                                   <circle cx="12" cy="7" r="4"></circle>
                                </svg>
                             </div>
                             <h2 className="text-gray-900 text-lg title-font font-medium mb-2">Contact</h2>
                          </div>
                          <div className="flex-grow">
                             <p className="leading-relaxed text-base">Lorem Ipsum bottle crucifix vinyl post-ironic four dollar
                                toast
                                vegan taxidermy. Gastropub indxgo juice poutine.</p>
                             <Link href="/contact"><a className="mt-3 text-indigo-500 inline-flex items-center">Example
                                <svg fill="none" stroke="currentColor"
                                     className="w-4 h-4 ml-2 w-4 animate-ping h-4 ml-2" viewBox="0 0 24 24">
                                   <path d="M5 12h14M12 5l7 7-7 7"></path>
                                </svg>
                             </a></Link>
                          </div>
                       </div>
                    </div>
                    <div className="p-4 md:w-1/3">
                       <div className="flex rounded-lg h-full bg-gray-100 p-8 flex-col">
                          <div className="flex items-center mb-3">
                             <div
                               className="
                               w-8 h-8 mr-3
                               inline-flex
                               items-center
                               justify-center
                               rounded-full
                               bg-indigo-500
                               text-white
                               flex-shrink-0
                               sm:w-15 sm:order-none order-first sm:h-15 animate-bounce  h-15 w-15 sm:ml-1 inline-flex items-center justify-center rounded-full bg-indigo-700 text-white flex-shrink-0
                               ">
                                <svg fill="none" stroke="currentColor" className="w-5 h-5 w-4" viewBox="0 0 24 24">
                                   <circle cx="6" cy="6" r="3"></circle>
                                   <circle cx="6" cy="18" r="3"></circle>
                                   <path d="M20 4L8.12 15.88M14.47 14.48L20 20M8.12 8.12L12 12"></path>
                                </svg>
                             </div>
                             <h2 className="text-gray-900 text-lg title-font font-medium mb-2">F.A.Q</h2>
                          </div>
                          <div className="flex-grow">
                             <p className="leading-relaxed text-base">Lorem Ipsum bottle crucifix vinyl post-ironic four dollar
                                toast
                                vegan taxidermy. Gastropub indxgo juice poutine.</p>
                             <Link href="/faq"><a className="mt-3 text-indigo-500 inline-flex items-center">Example
                                <svg fill="none" stroke="currentColor"
                                     className="w-4 h-4 ml-2 w-4 animate-ping h-4 ml-2" viewBox="0 0 24 24">
                                   <path d="M5 12h14M12 5l7 7-7 7"></path>
                                </svg>
                             </a></Link>
                          </div>
                       </div>
                    </div>
                 </div>
              </div>
           </section>
           <section className="text-gray-600 body-font">
              <div className="container px-5 py-24 pb-24 mx-auto">
                 <div className="flex flex-wrap -m-4">
                    <div className="p-4 md:w-1/3">
                       <div className="flex rounded-lg h-full bg-gray-100 p-8 flex-col">
                          <div className="flex items-center mb-3">
                             <div
                               className="
                               w-8 h-8 mr-3
                               inline-flex
                               items-center
                               justify-center
                               rounded-full
                               bg-indigo-500
                               text-white
                               flex-shrink-0
                               sm:w-15 sm:order-none order-first sm:h-15 animate-bounce  h-15 w-15 sm:ml-1 inline-flex items-center justify-center rounded-full bg-indigo-700 text-white flex-shrink-0
                               ">
                                <svg fill="none" stroke="currentColor" className="w-5 h-5" viewBox="0 0 24 24">
                                   <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                                </svg>
                             </div>
                             <h2 className="text-gray-900 text-lg title-font font-medium mb-2">Navbar</h2>
                          </div>
                          <div className="flex-grow">
                             <p className="leading-relaxed text-base">Lorem Ipsum bottle crucifix vinyl post-ironic four dollar
                                toast
                                vegan taxidermy. Gastropub indxgo juice poutine.</p>
                             <Link href="navbar"><a className="mt-3 text-indigo-500 inline-flex items-center">Example
                                <svg fill="none" stroke="currentColor"
                                     className="w-4 h-4 ml-2 w-4 animate-ping h-4 ml-2" viewBox="0 0 24 24">
                                   <path d="M5 12h14M12 5l7 7-7 7"></path>
                                </svg>
                             </a></Link>
                          </div>
                       </div>
                    </div>
                    <div className="p-4 md:w-1/3">
                       <div className="flex rounded-lg h-full bg-gray-100 p-8 flex-col">
                          <div className="flex items-center mb-3">
                             <div
                               className="
                               w-8 h-8 mr-3
                               inline-flex
                               items-center
                               justify-center
                               rounded-full
                               bg-indigo-500
                               text-white
                               flex-shrink-0
                               sm:w-15 sm:order-none order-first sm:h-15 animate-bounce  h-15 w-15 sm:ml-1 inline-flex items-center justify-center rounded-full bg-indigo-700 text-white flex-shrink-0
                               ">
                                <svg fill="none" stroke="currentColor" className="w-5 h-5" viewBox="0 0 24 24">
                                   <path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"></path>
                                   <circle cx="12" cy="7" r="4"></circle>
                                </svg>
                             </div>
                             <h2 className="text-gray-900 text-lg title-font font-medium mb-2">Product</h2>
                          </div>
                          <div className="flex-grow">
                             <p className="leading-relaxed text-base">Lorem Ipsum bottle crucifix vinyl post-ironic four dollar
                                toast
                                vegan taxidermy. Gastropub indxgo juice poutine.</p>
                             <Link href="/product"><a className="mt-3 text-indigo-500 inline-flex items-center">Example
                                <svg fill="none" stroke="currentColor"
                                     className="w-4 h-4 ml-2 w-4 animate-ping h-4 ml-2" viewBox="0 0 24 24">
                                   <path d="M5 12h14M12 5l7 7-7 7"></path>
                                </svg>
                             </a></Link>
                          </div>
                       </div>
                    </div>
                    <div className="p-4 md:w-1/3">
                       <div className="flex rounded-lg h-full bg-gray-100 p-8 flex-col">
                          <div className="flex items-center mb-3">
                             <div
                               className="
                               w-8 h-8 mr-3
                               inline-flex
                               items-center
                               justify-center
                               rounded-full
                               bg-indigo-500
                               text-white
                               flex-shrink-0
                               sm:w-15 sm:order-none order-first sm:h-15 animate-bounce  h-15 w-15 sm:ml-1 inline-flex items-center justify-center rounded-full bg-indigo-700 text-white flex-shrink-0
                               ">
                                <svg fill="none" stroke="currentColor" className="w-5 h-5 w-4" viewBox="0 0 24 24">
                                   <circle cx="6" cy="6" r="3"></circle>
                                   <circle cx="6" cy="18" r="3"></circle>
                                   <path d="M20 4L8.12 15.88M14.47 14.48L20 20M8.12 8.12L12 12"></path>
                                </svg>
                             </div>
                             <h2 className="text-gray-900 text-lg title-font font-medium mb-2">Dynamic Route</h2>
                          </div>
                          <div className="flex-grow">
                             <p className="leading-relaxed text-base">Lorem Ipsum bottle crucifix vinyl post-ironic four dollar
                                toast
                                vegan taxidermy. Gastropub indxgo juice poutine.</p>
                             <Link href="/text"><a className="mt-3 text-indigo-500 inline-flex items-center">Example
                                <svg fill="none" stroke="currentColor"
                                     className="w-4 h-4 ml-2 w-4 animate-ping h-4 ml-2" viewBox="0 0 24 24">
                                   <path d="M5 12h14M12 5l7 7-7 7"></path>
                                </svg>
                             </a></Link>
                          </div>
                       </div>
                    </div>
                 </div>
              </div>
           </section>
        </main>

        <footer className={styles.footer}>
           Made by ISA with
           <svg className="
           w-6 h-6 ml-2
           sm:w-15 w-4 animate-ping h-4 ml-2
           " fill="none" stroke="red" viewBox="0 0 24 24"
                xmlns="http://www.w3.org/2000/svg">
              <path d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"></path>
           </svg>
           <span className={styles.logo}>
          </span>
        </footer>
     </div>
   )
}
