import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Cards from "./components/Cards";

export default function Home() {

  class CardProps{
    constructor(title, content, link) {
      this.title = title;
      this.content = content;
      this.link = link;
    }
    getTitle() {
      return this.title;
    }
    getContent() {
      return this.content;
    }
    getLink() {
      return this.link;
    }
  }
  const firstRow = new CardProps(
    ['Card', 'Contact', 'Faq'],
    [
      'This is the content of the first card',
      'This is the content of the second card',
      'This is the content of the third card'
    ],
    ['card', 'contact', 'faq']
  );
  const secondRow = new CardProps(
    ['Navbar', 'Pruduct', 'Text'],
    [
      'This is the content of the first card',
      'This is the content of the second card',
      'This is the content of the third card'
    ],
    ['navbar', 'product', 'text']
  );
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main className="mt-24">
        <div className="flex flex-col text-center w-full mb-20">
          <h2 className="text-xs text-indigo-500 tracking-widest font-medium title-font mb-1">BASIT TAILWIND
            COMPONENTLERI</h2>
          <h1 className="sm:text-3xl text-2xl font-medium title-font text-gray-900">ISA OZSOY</h1>
        </div>
        <Cards title={firstRow.getTitle()} content={firstRow.content} link={firstRow.getLink()}/>
        <Cards title={secondRow.getTitle()} content={secondRow.getContent()} link={secondRow.getLink()}/>
      </main>
      <footer className={styles.footer}>
        Made by ISA with
        <svg className="
           w-6 h-6 ml-2
           sm:w-15 w-4 animate-ping h-4 ml-2
           " fill="none" stroke="red" viewBox="0 0 24 24"
             xmlns="http://www.w3.org/2000/svg">
          <path
            d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"></path>
        </svg>
        <span className={styles.logo}>
          </span>
      </footer>
    </div>
  )
}
